### homepage
GET http://localhost:5000/api/auth/
content-type: application/json

### login
POST  http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "saidali@live.com",
    "password": "pass123"
}

### renew refresh token
POST http://localhost:4000/api/auth/refresh-token
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTA4NzcsImV4cCI6MTY2MDg0ODQ3NywiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.bI2A0bF8ngmQaHXXsOmQDF1Jxsjuz2B9l2gB4oTEMUU"
}

### logout
POST http://localhost:4000/api/auth/logout
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTA4NzcsImV4cCI6MTY2MDg0ODQ3NywiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.bI2A0bF8ngmQaHXXsOmQDF1Jxsjuz2B9l2gB4oTEMUU"
}


### register
POST http://localhost:4000/api/auth/register
content-type: application/json

{
    "name": "ali",
    "email": "said.ali10@outlook.com",
    "mobile": "0441551027",
    "password": "pass"
}

### forgot password
POST http://localhost:4000/api/auth/forgot-password
content-type: application/json

{
    "email": "said.ali10@outlook.com"
}


### reset password
POST http://localhost:4000/api/auth/forgot-password/6107b5d1eb46bdf8aa7e6116/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhaWQuYWxpMTBAb3V0bG9vay5jb20iLCJpZCI6IjYxMDdiNWQxZWI0NmJkZjhhYTdlNjExNiIsImlhdCI6MTYyNzg5NjQyMSwiZXhwIjoxNjI3ODk3MDIxLCJhdWQiOiI2MTA3YjVkMWViNDZiZGY4YWE3ZTYxMTYiLCJpc3MiOiJodHRwczovL3d3dy5teXdlYnNpdGUuY29tIn0.qoHVyMKvPg7I5dRohR9vASP2YAabAhwbjllFihSE8Uk
content-type: application/json

{
    "password": "heyyy"
}

### verify account
GET http://localhost:4000/api/auth/verify-account/6107b5d1eb46bdf8aa7e6116/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4OTUyNDksImV4cCI6MTYyNzg5NTg0OSwiYXVkIjoidW5kZWZpbmVkIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.leV6B0dNmgzOTrX_mTC63NoJMrldwseBtUw-uDi6VFA