### login via the auth service for access and refresh token pairs
POST  http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "john.barnes1983@outlook.com",
    "password": "pass"
}

### create post
POST  http://localhost:5000/api/posts/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

{
    "content": "", 
    "imageUri": "https://drive.google.com/thumbnail?id=1JLZFgI4aipro3DDx3LCdVjmsE71_l-Le"
}

### create post
PATCH  http://localhost:5000/api/posts/611d19f4810a7ab8981c74ac
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

{
    "content": "hit 'em up"
}

### fetch post data by id
GET  http://localhost:5000/api/posts/612109ceb96e740039045c59
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### create comment on a post by id
POST  http://localhost:5000/api/posts/611d19f4810a7ab8981c74ac/comment/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

{
    "comment":"yooooo!"
}

### fetch posts comments
GET  http://localhost:5000/api/posts/611d19f4810a7ab8981c74ac/comments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### fetch user posts
GET  http://localhost:5000/api/posts/users/611d2138a972c0741b74e57c/fetchPosts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA


### fetch posts liked by user
GET  http://localhost:5000/api/posts/users/611d1765a972c0741b74e578/fetchLikedPosts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### fetch likes for post
GET  http://localhost:5000/api/posts/611d19f4810a7ab8981c74ac/likes
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### like a post by id
POST  http://localhost:5000/api/posts/611d19f4810a7ab8981c74ac/like
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### unlike a post by id
DELETE  http://localhost:5000/api/posts/611d19f4810a7ab8981c74ac/unlike
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

