### login via the auth service for access and refresh token pairs
POST  http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "said@gmail.com",
    "password": "said"
}

### homepage
GET http://localhost:5000
content-type: application/json

### create profile
POST  http://localhost:5000/api/profiles/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk5ODQ4OTQsImV4cCI6MTYzMDE1NzY5NCwiYXVkIjoiNjEyNzk4MWExZmY4MzYwMDNhMDBlYzNjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.ZHCj4zwjcKIJj0Yk2uShnWH-XQ0CDgL0oBsWtpzGJ7g

{
    "username":"si3iid",
    "name":"said",
    "profilePicture":"https://yt3.ggpht.com/yti/ANoDKi585jBh0-kAY3piX6ZiulL6_HbqQESafmkbnNnU-Q=s108-c-k-c0x00ffffff-no-rj",
    "bio":""
}
###6127981a1ff836003a00ec3c
### fetch profile data by userId
GET  http://localhost:5000/api/profiles/users/612a6449b4f6710041cd0cd7
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNjgzODUsImV4cCI6MTYzMDM0MTE4NSwiYXVkIjoiNjEyYTY0NDliNGY2NzEwMDQxY2QwY2Q3IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.UJ_vuSFCsrf5LyYof_xF6jfyXlhDTZhdiMwjD0eD0JY

### fetch profile data by username
GET  http://localhost:5000/api/profiles/user?username=si3iid
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### fetch profile data by name
GET  http://localhost:5000/api/profiles/user?name=said
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

### update profile
PATCH  http://localhost:5000/api/profiles/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk1NTQ0MTgsImV4cCI6MTYyOTcyNzIxOCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.2Gv3oEX4N2mIvJ_MpuKqjAC2c9plK2dTJbLtcbD9CuA

{
    "username":"sayid",
    "name":"Said",
    "profilePicture":"https://yt3.ggpht.com/yti/ANoDKi585jBh0-kAY3piX6ZiulL6_HbqQESafmkbnNnU-Q=s108-c-k-c0x00ffffff-no-rj"
}

### fetch profile data by name
GET  http://localhost:5000/api/profiles/me
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk5NzUwNTYsImV4cCI6MTYzMDE0Nzg1NiwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.bosx6UMxBNgeI2BxRrsHl6s9mWbxtjQ4I_3eLF_jZkk
