require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.5'

target 'Instagram' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSecureStorage', :path => '../node_modules/react-native-secure-storage'
  pod 'rn-fetch-blob',  :path => '../node_modules/rn-fetch-blob'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'InstagramTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 # use_flipper!({ 'Flipper' => '0.87.0' })
 # post_install do |installer|
 #   flipper_post_install(installer)
 # end
end

target 'Instagram-tvOS' do
  # Pods for Instagram-tvOS

  target 'Instagram-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
